// <auto-generated />
using System;
using EDStationDatabase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EDStationDatabase.Migrations
{
    [DbContext(typeof(EDAssetsContext))]
    [Migration("20250415165041_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EDStationDatabase.Models.Category.Allegiance", b =>
                {
                    b.Property<int>("AllegianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllegianceId"));

                    b.Property<string>("AllegianceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AllegianceId");

                    b.ToTable("Allegiances");

                    b.HasData(
                        new
                        {
                            AllegianceId = 1,
                            AllegianceName = "Aisling Duval"
                        },
                        new
                        {
                            AllegianceId = 2,
                            AllegianceName = "Arissa Lavingy-Duval"
                        },
                        new
                        {
                            AllegianceId = 3,
                            AllegianceName = "Denton Patreus"
                        },
                        new
                        {
                            AllegianceId = 4,
                            AllegianceName = "Zemina Torval"
                        },
                        new
                        {
                            AllegianceId = 5,
                            AllegianceName = "Jerome Archer"
                        },
                        new
                        {
                            AllegianceId = 6,
                            AllegianceName = "Felicia Winters"
                        },
                        new
                        {
                            AllegianceId = 7,
                            AllegianceName = "Edmund Mahon"
                        },
                        new
                        {
                            AllegianceId = 8,
                            AllegianceName = "Nakato Kaine"
                        },
                        new
                        {
                            AllegianceId = 9,
                            AllegianceName = "Archon Delaine"
                        },
                        new
                        {
                            AllegianceId = 10,
                            AllegianceName = "Li Yong-Rui"
                        },
                        new
                        {
                            AllegianceId = 11,
                            AllegianceName = "Parnav Antal"
                        },
                        new
                        {
                            AllegianceId = 12,
                            AllegianceName = "Yuri Grom"
                        },
                        new
                        {
                            AllegianceId = 13,
                            AllegianceName = "Independent"
                        },
                        new
                        {
                            AllegianceId = 14,
                            AllegianceName = "Pilot's Federation"
                        });
                });

            modelBuilder.Entity("EDStationDatabase.Models.Category.Economy", b =>
                {
                    b.Property<int>("EconomyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EconomyId"));

                    b.Property<string>("EconomyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EconomyId");

                    b.ToTable("Economies");

                    b.HasData(
                        new
                        {
                            EconomyId = 1,
                            EconomyName = "Agriculture"
                        },
                        new
                        {
                            EconomyId = 2,
                            EconomyName = "Colony"
                        },
                        new
                        {
                            EconomyId = 3,
                            EconomyName = "Extraction"
                        },
                        new
                        {
                            EconomyId = 4,
                            EconomyName = "High Tech"
                        },
                        new
                        {
                            EconomyId = 5,
                            EconomyName = "Industrial"
                        },
                        new
                        {
                            EconomyId = 6,
                            EconomyName = "Military"
                        },
                        new
                        {
                            EconomyId = 7,
                            EconomyName = "Refinery"
                        },
                        new
                        {
                            EconomyId = 8,
                            EconomyName = "Service"
                        },
                        new
                        {
                            EconomyId = 9,
                            EconomyName = "Terraforming"
                        },
                        new
                        {
                            EconomyId = 10,
                            EconomyName = "Tourism"
                        },
                        new
                        {
                            EconomyId = 11,
                            EconomyName = "Prison Colony"
                        });
                });

            modelBuilder.Entity("EDStationDatabase.Models.Category.StationType", b =>
                {
                    b.Property<int>("StationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationTypeId"));

                    b.Property<string>("StationTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StationTypeId");

                    b.ToTable("StationType");

                    b.HasData(
                        new
                        {
                            StationTypeId = 1,
                            StationTypeName = "Coriolis"
                        },
                        new
                        {
                            StationTypeId = 2,
                            StationTypeName = "Orbis"
                        },
                        new
                        {
                            StationTypeId = 3,
                            StationTypeName = "Ocellus"
                        },
                        new
                        {
                            StationTypeId = 4,
                            StationTypeName = "Outpost"
                        },
                        new
                        {
                            StationTypeId = 5,
                            StationTypeName = "Planetary Outpost"
                        },
                        new
                        {
                            StationTypeId = 6,
                            StationTypeName = "Planetary Port"
                        },
                        new
                        {
                            StationTypeId = 7,
                            StationTypeName = "Planetary Surface Port"
                        },
                        new
                        {
                            StationTypeId = 8,
                            StationTypeName = "Planetary Settlement"
                        },
                        new
                        {
                            StationTypeId = 9,
                            StationTypeName = "Asteroid Base"
                        });
                });

            modelBuilder.Entity("EDStationDatabase.Models.Category.Superpower", b =>
                {
                    b.Property<int>("SuperpowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperpowerId"));

                    b.Property<string>("SuperpowerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuperpowerId");

                    b.ToTable("Superpowers");

                    b.HasData(
                        new
                        {
                            SuperpowerId = 1,
                            SuperpowerName = "Empire"
                        },
                        new
                        {
                            SuperpowerId = 2,
                            SuperpowerName = "Federation"
                        },
                        new
                        {
                            SuperpowerId = 3,
                            SuperpowerName = "Alliance"
                        },
                        new
                        {
                            SuperpowerId = 4,
                            SuperpowerName = "Independent"
                        });
                });

            modelBuilder.Entity("EDStationDatabase.Models.StationBookmark", b =>
                {
                    b.Property<int>("StationBookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationBookmarkId"));

                    b.Property<int?>("AllegianceId")
                        .HasColumnType("int");

                    b.Property<int?>("EconomyId")
                        .HasColumnType("int");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StationTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SuperpowerId")
                        .HasColumnType("int");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StationBookmarkId");

                    b.HasIndex("AllegianceId");

                    b.HasIndex("EconomyId");

                    b.HasIndex("StationTypeId");

                    b.HasIndex("SuperpowerId");

                    b.ToTable("StationBookmarks");

                    b.HasData(
                        new
                        {
                            StationBookmarkId = 1,
                            AllegianceId = 13,
                            EconomyId = 7,
                            StationName = "Low City",
                            StationTypeId = 3,
                            SystemName = "HR 1980"
                        },
                        new
                        {
                            StationBookmarkId = 2,
                            AllegianceId = 10,
                            EconomyId = 4,
                            StationName = "Ray Gateway",
                            StationTypeId = 1,
                            SystemName = "Diaguandri"
                        },
                        new
                        {
                            StationBookmarkId = 3,
                            AllegianceId = 13,
                            EconomyId = 6,
                            StationName = "Copernicus Observatory",
                            StationTypeId = 1,
                            SystemName = "Asterope"
                        });
                });

            modelBuilder.Entity("EDStationDatabase.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EDStationDatabase.Models.StationBookmark", b =>
                {
                    b.HasOne("EDStationDatabase.Models.Category.Allegiance", "Allegiance")
                        .WithMany()
                        .HasForeignKey("AllegianceId");

                    b.HasOne("EDStationDatabase.Models.Category.Economy", "Economy")
                        .WithMany()
                        .HasForeignKey("EconomyId");

                    b.HasOne("EDStationDatabase.Models.Category.StationType", "StationType")
                        .WithMany()
                        .HasForeignKey("StationTypeId");

                    b.HasOne("EDStationDatabase.Models.Category.Superpower", "Superpower")
                        .WithMany()
                        .HasForeignKey("SuperpowerId");

                    b.Navigation("Allegiance");

                    b.Navigation("Economy");

                    b.Navigation("StationType");

                    b.Navigation("Superpower");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EDStationDatabase.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EDStationDatabase.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDStationDatabase.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EDStationDatabase.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
